### ISSUE TITLE
Add generator for building basic config

### ISSUE THREAD

**Issue by rpelyush** [rpelyush/gardien#18]
Generated config example:
```elixir
config :gardien, current_user: :current_user, unauth_handler: handler_func, logger: true
```

**Comment by rpelyush** [comment]
@banzay for now 
```elixir
config :gardien, current_user: :current_user, unauth_handler: handler_func
```
will suffice. No need to generate application policy until we define how it should work!

**Comment by rpelyush** [comment]
@banzay before implementing this issue please describe here how this generator (mix task) will work.

**Comment by rpelyush** [comment]
@banzay when you've finished this issue you can work on this one https://github.com/rpelyush/gardien/issues/24

**Comment by banzay** [comment]
I have doubts it will be useful.Writing a row into config file is too much magic.
Do you agree?

**Comment by rpelyush** [comment]
I see no magic in generating config, but for now we'll skip it. Simple copy&paste will work (as you suggested)
