### ISSUE TITLE
Rename confusing function extract_user to extract_user_key 

### ISSUE THREAD

**Issue by banzay** [rpelyush/gardien#33]
```
defp extract_user(%{current_user: user} = _options) when is_nil(user) do
    Application.get_env(:gardien, :current_user, :current_user)
  end
  defp extract_user(%{current_user: user} = _options), do: user

  defp extract_user(conn, %{current_user: user} = _options) do
    Map.get(conn.assigns, user)
  end
```

Function names are same, but first 2 functions return Atom, and last returns User.
Same goes for extract_resource. 

I suggest renaming first two methods to extract_user_key.

Do you agree, @rpelyush ?

**Comment by rpelyush** [comment]
Yes.
But maybe not ```extract_..._key``` but  ```extract_user_option``` and ```extract_resource_option```?
