### ISSUE TITLE
Make :resource option optional

### ISSUE THREAD

**Issue by banzay** [rpelyush/gardien#36]
Currently error is thrown if :resource is nil.
I'd like to cover cases in which authorization will not depend on particular database entity, but only on user.
@rpelyush

**Comment by rpelyush** [comment]
https://github.com/rpelyush/gardien/issues/8

**Comment by banzay** [comment]
It should be mentioned in the doc (I'll add comment).

**Comment by rpelyush** [comment]
As far as I remember it's already mentioned.
