### ISSUE TITLE
Handle cases when required params are missing in conn or options

### ISSUE THREAD

**Issue by rpelyush** [rpelyush/gardien#6]
In order to successfully authorize conn ```:curren_user```, ```:resource``` and  ```policy``` should be specified and present in ```conn``` and ```options```

**Comment by banzay** [comment]
Can I do this?

**Comment by rpelyush** [comment]
We should also consider cases when ```current_user``` is not available in ```conn.assigns```. This means that user ```was not authenticated```, hence such connection is not authorized and we should call ```unauth_handler```.
