### ISSUE TITLE
Handle authorization when resource is not required

### ISSUE THREAD

**Issue by rpelyush** [rpelyush/gardien#8]
It should be possible to authorize connection based on current user only when resource is not needed (based on current user role etc)

**Comment by banzay** [comment]
Can I do this?

**Comment by rpelyush** [comment]
Of course. Though, right now I'm working on https://github.com/rpelyush/gardien/issues/3 and I'm not sure whether you should start this issue before I'll finish my.

**Comment by banzay** [comment]
maybe this?Add generator for building basic config (and application policy
example) #18

2016-03-29 11:55 GMT+03:00 Roman Pelyushkevych <notifications@github.com>:

> Of course. Though, right now I'm working on #3
> <https://github.com/rpelyush/gardien/issues/3> and I'm not sure whether
> you should start this issue before I'll finish my.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/rpelyush/gardien/issues/8#issuecomment-202784431>
>



-- 
Слава Вареникам!

**Comment by rpelyush** [comment]
yes

**Comment by rpelyush** [comment]
For now, in case actual resource is not required user can pass simple struct as a resource option.
Resource option will stay required.
