### ISSUE TITLE
Allow for extended policy configuration (usage)

### ISSUE THREAD

**Issue by rpelyush** [rpelyush/gardien#9]
For cases when user and record is not enough to authorize connection it should be possible to do authorization using several records (extended context)

**Comment by rpelyush** [comment]
I'm thinking about something like this:
```elixir
# authorize user rights to perform (controller) action(s) on/in context
plug Gardien, context: [:post, :newspaper], policy: PostPolicy
# resulting context map %{post: %Post{}, newspaper: %Newspaper{}}

# policy function example
defmodule PostPolicy do
  def update(user, context) do
    context.post.id == user.id && context.newspaper.user_id == user.id
  end
end
``` 

And with one resource:
```elixir
# authorize user rights to perform (controller) action(s) on resource
plug Gardien, resource: :post, policy: PostPolicy

# policy function example
defmodule PostPolicy do
  def update(user, resource) do
    resource.id == user.id
  end
end
```

Usually we authorize user access based on one resource, so probably I would leave ability to pass ```resource``` key.
As to ```context:``` I'm not totally sure about it, though, I don't like idea of ```resources``` key.
What I do like about ```context``` is that it makes some sense when to look at policies as strategies (strategy/policy pattern).
Perhaps it would be nice to have only ```resource``` or ```context```, something like:
```elixir
plug Gardien, context: :post, policy: PostPolicy
# resulting context map %{post: %Post{}}
```
but taking into account that most of the times authorization is performed on one resource, I'm not sure
whether accessing one resource through context won't be too cumbersome, e.g:
```elixir
def update(user, context) do # instead of def update(user, resource)
   context.post.id == user.id # instead of resource.id == user.id
end
```

So, should we live ```resource``` in options or introduce ```context```? Or have both, ```resource``` for "most of the times" cases and ```context``` for cases when we need more than one resource? Or this ```context``` stuff is useless?

@romkor @banzay any thoughts?

**Comment by romkor** [comment]
For Policy can suggest something like this:
```elixir
defmodule PostPolicy do
  def update(user, post, newspaper) do
    newspaper.user_id == user.id && post.newspaper_id == newspaper.id
  end
end
```

**Comment by rpelyush** [comment]
But then we'll have to deal with arguments order, I wouldn't want that.

**Comment by rpelyush** [comment]
Probably I would go with having two strategies: ```resource``` and ```context``` (with possibility to use only one at a time). It would be up to user to decide what approach works better for him/her.
Also in case resource is not needed https://github.com/rpelyush/gardien/issues/8, ```context``` strategy would be used by default and ```context``` would eql to ```conn``` (this should work for cases when user deliberately wants ```conn``` as a max. possible context in policy)

**Comment by banzay** [comment]
I like how Pundit handles this (it allows to pass *any* value to Policy).
How about leaving only `context:` param and passing it a single atom OR anonymous function?

Possible implementation: 
```
plug Gardien, context: :post, policy: PostPolicy
plug Gardien, context: fn(assigns) -> assigns.post.author end, policy: PostPolicy
plug Gardien, 
        context: fn(assigns) -> %CustomContext{author: assigns.post.author} end, 
        policy: PostPolicy
```

**Comment by rpelyush** [comment]
So in case we leave only ```context```, does it mean that in policy functions we'll have to access the actual resource by ```context.resource```?

**Comment by banzay** [comment]
context === resource is better than context.resource === resource 
imo

**Comment by rpelyush** [comment]
So we'll end up with this:
- we can use ```resource``` for cases when you want to deal ONLY with one resource (this is the most frequent case), e.g
```elixir
plug Gardien, resource: :post

# in policy function
def create(user, resource)
  resource.user_id == user.id
end
```
- we allow to use context for cases when you need more resources
```elixir
plug Gardien, context: [:post, :newspaper]
or
plug Gardien, context: :post

# in policy function
def create(user, context)
  context.post.id == user.id && context.newspaper.id == context.post.newspaper_id
end
```
- we allow to use anon. function as proposed by @banzay for ```context``` and ```resource```
- we allow for not specifying ```context``` or ```resource```. In that case we pass ```conn``` to policy function as a ```context```.
Yes?

**Comment by banzay** [comment]
It looks too complex. I'd drop this  -  `context: [:post, :newspaper]`,
and use `context` as parameter name everywhere - context: :post

This will lead to simpler API (a `context` which can be resource key OR function OR non-existent

**Comment by rpelyush** [comment]
So it's always:
```elixir
def create(user, context), do: context.post.id == user.id
```
and not:
```elixir
def create(user, resource), do: resource.id == user.id
```

**Comment by banzay** [comment]
I don't see the point in nesting here. 
`context: :post` used as `context.id` seems simpler. 
Resource is a context in this case.

**Comment by rpelyush** [comment]
Then we'll use only ```resource```.
